#!/bin/sh
export LD_LIBRARY_PATH=../.libs
IDX=tmp/testindex
rm -rf tmp
mkdir tmp
../zet -i -c ../config/psettings.xml -t HTML -f $IDX data/en_bing.html
# gdb -x gdb-run --args ../.libs/zet -n 10 -f $IDX --summary=tag microsoft
gdb  --args ../.libs/zet -n 10 -f $IDX --summary=tag microsoft

