#!/bin/sh
export LD_LIBRARY_PATH=../.libs
IDX=tmp/testindex
rm -f tmp
mkdir tmp
../zet -i -c ../config/psettings.xml -t HTML -f $IDX data/Che_Guevara data/Che_Guevara_Mausoleum data/Che_Guevara_in_popular_culture data/Guevarism 
echo guevara | ../zet -n 10 -f $IDX --summary=tag

